# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addNewUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addNewUser(object):
    def setupUi(self, addNewUser):
        addNewUser.setObjectName("addNewUser")
        addNewUser.resize(800, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addNewUser.sizePolicy().hasHeightForWidth())
        addNewUser.setSizePolicy(sizePolicy)
        addNewUser.setMinimumSize(QtCore.QSize(800, 800))
        addNewUser.setMaximumSize(QtCore.QSize(800, 800))
        addNewUser.setSizeIncrement(QtCore.QSize(0, 0))
        addNewUser.setStyleSheet("*{\n"
                                 "font-family: century gothic;\n"
                                 "font-size: 30px;\n"
                                 "background-color:#201f1f;\n"
                                 "}\n"
                                 "QFrame{\n"
                                 "background: #605E5C ;\n"
                                 "border-radius:10px;\n"
                                 "\n"
                                 "}\n"
                                 "QLabel{\n"
                                 "color:white;\n"
                                 "font-weight: bold;\n"
                                 "}\n"
                                 "QToolButton{\n"
                                 "background:white;\n"
                                 "border-radius:60px;\n"
                                 "}\n"
                                 "QLineEdit{\n"
                                 "background: transparent;\n"
                                 "border:none;\n"
                                 "color:BLACK;\n"
                                 "border-bottom:1px solid black;\n"
                                 "font-size:20px;\n"
                                 "}\n"
                                 "QPushButton{\n"
                                 "font-size:18px;\n"
                                 "font-weight:bold;\n"
                                 "color:white ;\n"
                                 "background:#201f1f;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "color:white;\n"
                                 "background-color:black;\n"
                                 "}\n"
                                 "#logoLabel{\n"
                                 "background:transparent;\n"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(addNewUser)
        self.centralwidget.setObjectName("centralwidget")
        self.addNewUserForm_frame = QtWidgets.QFrame(self.centralwidget)
        self.addNewUserForm_frame.setGeometry(QtCore.QRect(210, 130, 400, 600))
        self.addNewUserForm_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addNewUserForm_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.addNewUserForm_frame.setObjectName("addNewUserForm_frame")
        self.addNewUser_label = QtWidgets.QLabel(self.addNewUserForm_frame)
        self.addNewUser_label.setGeometry(QtCore.QRect(90, 100, 221, 40))
        self.addNewUser_label.setObjectName("addNewUser_label")
        self.username_field = QtWidgets.QLineEdit(self.addNewUserForm_frame)
        self.username_field.setGeometry(QtCore.QRect(80, 200, 240, 30))
        self.username_field.setText("")
        self.username_field.setObjectName("username_field")
        self.password_field = QtWidgets.QLineEdit(self.addNewUserForm_frame)
        self.password_field.setGeometry(QtCore.QRect(80, 260, 240, 30))
        self.password_field.setText("")
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.add_pushButton = QtWidgets.QPushButton(self.addNewUserForm_frame)
        self.add_pushButton.setGeometry(QtCore.QRect(120, 500, 160, 40))
        self.add_pushButton.setObjectName("add_pushButton")
        self.contactInfo_field = QtWidgets.QLineEdit(self.addNewUserForm_frame)
        self.contactInfo_field.setGeometry(QtCore.QRect(80, 330, 240, 30))
        self.contactInfo_field.setText("")
        self.contactInfo_field.setObjectName("contactInfo_field")
        self.address_field = QtWidgets.QLineEdit(self.addNewUserForm_frame)
        self.address_field.setGeometry(QtCore.QRect(80, 400, 240, 30))
        self.address_field.setText("")
        self.address_field.setObjectName("address_field")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(330, 70, 150, 100))
        self.logo_label.setStyleSheet("background: transparent;")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/logo/surveilialogo.PNG"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.logo_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.logo_toolButton.setGeometry(QtCore.QRect(340, 60, 120, 120))
        self.logo_toolButton.setText("")
        self.logo_toolButton.setObjectName("logo_toolButton")
        self.addNewUserForm_frame.raise_()
        self.logo_toolButton.raise_()
        self.logo_label.raise_()
        addNewUser.setCentralWidget(self.centralwidget)

        self.retranslateUi(addNewUser)
        QtCore.QMetaObject.connectSlotsByName(addNewUser)

    def retranslateUi(self, addNewUser):
        _translate = QtCore.QCoreApplication.translate
        addNewUser.setWindowTitle(_translate("addNewUser", "MainWindow"))
        self.addNewUser_label.setText(_translate("addNewUser", "ADD NEW USER"))
        self.username_field.setPlaceholderText(_translate("addNewUser", "Username"))
        self.password_field.setPlaceholderText(_translate("addNewUser", "Password"))
        self.add_pushButton.setText(_translate("addNewUser", "ADD"))
        self.contactInfo_field.setPlaceholderText(_translate("addNewUser", "Contact Info"))
        self.address_field.setPlaceholderText(_translate("addNewUser", "Address"))


import resource01

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    addNewUser = QtWidgets.QMainWindow()
    ui = Ui_addNewUser()
    ui.setupUi(addNewUser)
    addNewUser.show()
    sys.exit(app.exec_())
