# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QUrl

class Ui_adminMain(object):
    def setupUi(self, adminMain):
        adminMain.setObjectName("adminMain")
        adminMain.resize(1008, 832)
        adminMain.setMinimumSize(QtCore.QSize(1000, 800))
        adminMain.setStyleSheet("*{\n"
                                "font-family: century gothic;\n"
                                "background-color:#484644;\n"
                                "}\n"
                                "QLineEdit, QTextEdit{\n"
                                "background: #201f1f;\n"
                                "border:#201f1f;\n"
                                "color:white;\n"
                                "font-size:18px;\n"
                                "}\n"
                                "QLabel{\n"
                                "color: white;\n"
                                "font-size: 18px;\n"
                                "\n"
                                "}\n"
                                "QPushButton, QToolButton{\n"
                                "font-weight:bold;\n"
                                "color:white ;\n"
                                "background:#201f1f;\n"
                                "}\n"
                                "QPushButton:hover{\n"
                                "color:white;\n"
                                "background-color:black;\n"
                                "}\n"
                                "")
        self.centralwidget = QtWidgets.QWidget(adminMain)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aMenuBar = QtWidgets.QWidget(self.centralwidget)
        self.aMenuBar.setMinimumSize(QtCore.QSize(80, 0))
        self.aMenuBar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.aMenuBar.setStyleSheet("*{background: #201f1f;}\n"
                                    "QToolButton:hover{\n"
                                    "     background-color:#3b3a3a;\n"
                                    "}\n"
                                    "QToolButton:pressed{\n"
                                    "     background-color: #605E5C ;     \n"
                                    "}")
        self.aMenuBar.setObjectName("aMenuBar")
        self.aCamera_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aCamera_toolButton.setGeometry(QtCore.QRect(0, 10, 80, 71))
        self.aCamera_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aCamera_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aCamera_toolButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("camera-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aCamera_toolButton.setIcon(icon)
        self.aCamera_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aCamera_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aCamera_toolButton.setObjectName("aCamera_toolButton")
        self.aAlarm_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aAlarm_toolButton.setGeometry(QtCore.QRect(0, 80, 80, 71))
        self.aAlarm_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aAlarm_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aAlarm_toolButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("alarm-clock-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aAlarm_toolButton.setIcon(icon1)
        self.aAlarm_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aAlarm_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aAlarm_toolButton.setObjectName("aAlarm_toolButton")
        self.aStorage_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aStorage_toolButton.setGeometry(QtCore.QRect(0, 150, 80, 71))
        self.aStorage_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aStorage_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aStorage_toolButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("database-5-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aStorage_toolButton.setIcon(icon2)
        self.aStorage_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aStorage_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aStorage_toolButton.setObjectName("aStorage_toolButton")
        self.aAccount_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aAccount_toolButton.setGeometry(QtCore.QRect(0, 220, 80, 71))
        self.aAccount_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aAccount_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aAccount_toolButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("contacts-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aAccount_toolButton.setIcon(icon3)
        self.aAccount_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aAccount_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aAccount_toolButton.setObjectName("aAccount_toolButton")
        self.aHelp_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aHelp_toolButton.setGeometry(QtCore.QRect(0, 360, 80, 71))
        self.aHelp_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aHelp_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aHelp_toolButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("question-mark-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aHelp_toolButton.setIcon(icon4)
        self.aHelp_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aHelp_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aHelp_toolButton.setObjectName("aHelp_toolButton")
        self.aLogout_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aLogout_toolButton.setGeometry(QtCore.QRect(0, 430, 80, 71))
        self.aLogout_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aLogout_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aLogout_toolButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("logout-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aLogout_toolButton.setIcon(icon5)
        self.aLogout_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aLogout_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aLogout_toolButton.setObjectName("aLogout_toolButton")
        self.aUsers_toolButton = QtWidgets.QToolButton(self.aMenuBar)
        self.aUsers_toolButton.setGeometry(QtCore.QRect(0, 290, 80, 71))
        self.aUsers_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.aUsers_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.aUsers_toolButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("group-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aUsers_toolButton.setIcon(icon6)
        self.aUsers_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.aUsers_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aUsers_toolButton.setObjectName("aUsers_toolButton")
        self.aCamera_toolButton.raise_()
        self.aAlarm_toolButton.raise_()
        self.aStorage_toolButton.raise_()
        self.aAccount_toolButton.raise_()
        self.aUsers_toolButton.raise_()
        self.aHelp_toolButton.raise_()
        self.aLogout_toolButton.raise_()
        self.horizontalLayout_2.addWidget(self.aMenuBar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aTitleBar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aTitleBar.sizePolicy().hasHeightForWidth())
        self.aTitleBar.setSizePolicy(sizePolicy)
        self.aTitleBar.setMinimumSize(QtCore.QSize(0, 80))
        self.aTitleBar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.aTitleBar.setStyleSheet("background: #201f1f;\n"
                                     "font-size: 24px;")
        self.aTitleBar.setObjectName("aTitleBar")
        self.aTitle_label = QtWidgets.QLabel(self.aTitleBar)
        self.aTitle_label.setGeometry(QtCore.QRect(60, 30, 121, 21))
        self.aTitle_label.setObjectName("aTitle_label")
        self.verticalLayout_2.addWidget(self.aTitleBar)
        self.aStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.aStackedWidget.setStyleSheet("QTableWidget{ \n"
                                          "  width: 100%;\n"
                                          "   padding: 15px;\n"
                                          "  text-align: left;\n"
                                          "color: white;\n"
                                          "}\n"
                                          "\n"
                                          "\n"
                                          "QHeaderView::section {\n"
                                          "color:white;\n"
                                          "    background-color: #646464;\n"
                                          "    padding: 4px;\n"
                                          "    border: 1px solid black;\n"
                                          "    font-size: 16px;\n"
                                          "font-weight:bold;\n"
                                          "\n"
                                          "}\n"
                                          "\n"
                                          "QTableWidget {\n"
                                          "    gridline-color: black;\n"
                                          "    font-size: 14px;\n"
                                          "}\n"
                                          "\n"
                                          "QTableWidget QTableCornerButton::section {\n"
                                          "    background-color: #646464;\n"
                                          "    border: 1px solid black;\n"
                                          "}")
        self.aStackedWidget.setObjectName("aStackedWidget")
        self.aCamera_page = QtWidgets.QWidget()
        self.aCamera_page.setObjectName("aCamera_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.aCamera_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.aVideo_label = QtWidgets.QLabel(self.aCamera_page)
        self.aVideo_label.setText("")
        self.aVideo_label.setObjectName("aVideo_label")
        self.verticalLayout_7.addWidget(self.aVideo_label)
        self.aCamera_pushButton = QtWidgets.QPushButton(self.aCamera_page)
        self.aCamera_pushButton.setObjectName("aCamera_pushButton")
        self.verticalLayout_7.addWidget(self.aCamera_pushButton)
        self.aStackedWidget.addWidget(self.aCamera_page)
        self.aAlarm_page = QtWidgets.QWidget()
        self.aAlarm_page.setObjectName("aAlarm_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.aAlarm_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.aAlarmHistory_label = QtWidgets.QLabel(self.aAlarm_page)
        self.aAlarmHistory_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
                                               "font-size:24px")
        self.aAlarmHistory_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.aAlarmHistory_label.setObjectName("aAlarmHistory_label")
        self.horizontalLayout_3.addWidget(self.aAlarmHistory_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.aAlarm_tableWidget = QtWidgets.QTableWidget(self.aAlarm_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aAlarm_tableWidget.sizePolicy().hasHeightForWidth())
        self.aAlarm_tableWidget.setSizePolicy(sizePolicy)
        self.aAlarm_tableWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.aAlarm_tableWidget.setStyleSheet("QTableWidget{ \n"
                                              "  width: 100%;\n"
                                              "   padding: 15px;\n"
                                              "  text-align: left;\n"
                                              "color: white;\n"
                                              "}\n"
                                              "\n"
                                              "\n"
                                              "QHeaderView::section {\n"
                                              "color:white;\n"
                                              "    background-color: #646464;\n"
                                              "    padding: 4px;\n"
                                              "    border: 1px solid black;\n"
                                              "    font-size: 16px;\n"
                                              "font-weight:bold;\n"
                                              "\n"
                                              "}\n"
                                              "\n"
                                              "QTableWidget {\n"
                                              "    gridline-color: black;\n"
                                              "    font-size: 14px;\n"
                                              "}\n"
                                              "\n"
                                              "QTableWidget QTableCornerButton::section {\n"
                                              "    background-color: #646464;\n"
                                              "    border: 1px solid black;\n"
                                              "}")
        self.aAlarm_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aAlarm_tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.aAlarm_tableWidget.setObjectName("aAlarm_tableWidget")
        self.aAlarm_tableWidget.setColumnCount(5)
        self.aAlarm_tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.aAlarm_tableWidget.setHorizontalHeaderItem(4, item)
        self.aAlarm_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.aAlarm_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.aAlarm_tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.aAlarm_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.aAlarm_tableWidget.verticalHeader().setVisible(False)
        self.aAlarm_tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.horizontalLayout.addWidget(self.aAlarm_tableWidget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.aStackedWidget.addWidget(self.aAlarm_page)
        self.aStorage_page = QtWidgets.QWidget()
        self.aStorage_page.setObjectName("aStorage_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.aStorage_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.aStorage_label = QtWidgets.QLabel(self.aStorage_page)
        self.aStorage_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
                                          "font-size:24px")
        self.aStorage_label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.aStorage_label.setObjectName("aStorage_label")
        self.horizontalLayout_4.addWidget(self.aStorage_label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.aShow_label = QtWidgets.QLabel(self.aStorage_page)
        self.aShow_label.setObjectName("aShow_label")
        self.horizontalLayout_5.addWidget(self.aShow_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.aAnomalyClip_checkBox = QtWidgets.QCheckBox(self.aStorage_page)
        self.aAnomalyClip_checkBox.setStyleSheet("\n"
                                                 "font-size:16px;\n"
                                                 "color:white;")
        self.aAnomalyClip_checkBox.setObjectName("aAnomalyClip_checkBox")
        self.horizontalLayout_5.addWidget(self.aAnomalyClip_checkBox)
        self.aCameraFeed_checkBox = QtWidgets.QCheckBox(self.aStorage_page)
        self.aCameraFeed_checkBox.setStyleSheet("\n"
                                                "font-size:16px;\n"
                                                "color:white;")
        self.aCameraFeed_checkBox.setIconSize(QtCore.QSize(30, 30))
        self.aCameraFeed_checkBox.setChecked(False)
        self.aCameraFeed_checkBox.setAutoRepeat(False)
        self.aCameraFeed_checkBox.setAutoExclusive(False)
        self.aCameraFeed_checkBox.setTristate(False)
        self.aCameraFeed_checkBox.setObjectName("aCameraFeed_checkBox")
        self.horizontalLayout_5.addWidget(self.aCameraFeed_checkBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.aStorage_tableWidget = QtWidgets.QTableWidget(self.aStorage_page)
        self.aStorage_tableWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.aStorage_tableWidget.setStyleSheet("QTableWidget{ \n"
                                                "  width: 100%;\n"
                                                "   padding: 15px;\n"
                                                "  text-align: left;\n"
                                                "color: white;\n"
                                                "}\n"
                                                "\n"
                                                "\n"
                                                "QHeaderView::section {\n"
                                                "color:white;\n"
                                                "    background-color: #646464;\n"
                                                "    padding: 4px;\n"
                                                "    border: 1px solid black;\n"
                                                "    font-size: 16px;\n"
                                                "font-weight:bold;\n"
                                                "\n"
                                                "}\n"
                                                "\n"
                                                "QTableWidget {\n"
                                                "    gridline-color: black;\n"
                                                "    font-size: 14px;\n"
                                                "}\n"
                                                "\n"
                                                "QTableWidget QTableCornerButton::section {\n"
                                                "    background-color: #646464;\n"
                                                "    border: 1px solid black;\n"
                                                "}")
        self.aStorage_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aStorage_tableWidget.setObjectName("aStorage_tableWidget")
        self.aStorage_tableWidget.setColumnCount(4)
        self.aStorage_tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aStorage_tableWidget.setHorizontalHeaderItem(3, item)
        self.aStorage_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.aStorage_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.aStorage_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.aStorage_tableWidget.verticalHeader().setVisible(False)
        self.aStorage_tableWidget.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_6.addWidget(self.aStorage_tableWidget)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.aStackedWidget.addWidget(self.aStorage_page)
        self.aAccount_page = QtWidgets.QWidget()
        self.aAccount_page.setObjectName("aAccount_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.aAccount_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.aAccount_form = QtWidgets.QFormLayout()
        self.aAccount_form.setObjectName("aAccount_form")
        self.aAccountInfo_label = QtWidgets.QLabel(self.aAccount_page)
        self.aAccountInfo_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
                                              "font-size:24px;")
        self.aAccountInfo_label.setObjectName("aAccountInfo_label")
        self.aAccount_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.aAccountInfo_label)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.aAccount_form.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem11)
        self.aUsername_label = QtWidgets.QLabel(self.aAccount_page)
        self.aUsername_label.setObjectName("aUsername_label")
        self.aAccount_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.aUsername_label)
        self.aUsername_lineEdit = QtWidgets.QLineEdit(self.aAccount_page)
        self.aUsername_lineEdit.setObjectName("aUsername_lineEdit")
        self.aAccount_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.aUsername_lineEdit)
        self.aPassword_label = QtWidgets.QLabel(self.aAccount_page)
        self.aPassword_label.setObjectName("aPassword_label")
        self.aAccount_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.aPassword_label)
        self.aPassword_lineEdit = QtWidgets.QLineEdit(self.aAccount_page)
        self.aPassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.aPassword_lineEdit.setObjectName("aPassword_lineEdit")
        self.aAccount_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.aPassword_lineEdit)
        self.aContactInfo_label = QtWidgets.QLabel(self.aAccount_page)
        self.aContactInfo_label.setObjectName("aContactInfo_label")
        self.aAccount_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.aContactInfo_label)
        self.aContactInfo_lineEdit = QtWidgets.QLineEdit(self.aAccount_page)
        self.aContactInfo_lineEdit.setObjectName("aContactInfo_lineEdit")
        self.aAccount_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.aContactInfo_lineEdit)
        self.aAddress_label = QtWidgets.QLabel(self.aAccount_page)
        self.aAddress_label.setObjectName("aAddress_label")
        self.aAccount_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.aAddress_label)
        self.aAddress_lineEdit = QtWidgets.QTextEdit(self.aAccount_page)
        self.aAddress_lineEdit.setObjectName("aAddress_lineEdit")
        self.aAccount_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.aAddress_lineEdit)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.aAccount_form.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem12)
        self.aEdit_pushButton = QtWidgets.QPushButton(self.aAccount_page)
        self.aEdit_pushButton.setStyleSheet("FONT-SIZE: 18PX;")
        self.aEdit_pushButton.setObjectName("aEdit_pushButton")
        self.aAccount_form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.aEdit_pushButton)
        self.horizontalLayout_7.addLayout(self.aAccount_form)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.aStackedWidget.addWidget(self.aAccount_page)
        self.aUsers_page = QtWidgets.QWidget()
        self.aUsers_page.setObjectName("aUsers_page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.aUsers_page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.aUserInfo_label = QtWidgets.QLabel(self.aUsers_page)
        self.aUserInfo_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
                                           "font-size:24px;FONT-WEIGHT:BOLD;")
        self.aUserInfo_label.setObjectName("aUserInfo_label")
        self.horizontalLayout_8.addWidget(self.aUserInfo_label)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem16 = QtWidgets.QSpacerItem(55, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.aUserAdd_pushButton = QtWidgets.QPushButton(self.aUsers_page)
        self.aUserAdd_pushButton.setObjectName("aUserAdd_pushButton")
        self.horizontalLayout_9.addWidget(self.aUserAdd_pushButton)
        self.aUserDelete_pushButton = QtWidgets.QPushButton(self.aUsers_page)
        self.aUserDelete_pushButton.setObjectName("aUserDelete_pushButton")
        self.horizontalLayout_9.addWidget(self.aUserDelete_pushButton)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.aUser_tableWidget = QtWidgets.QTableWidget(self.aUsers_page)
        self.aUser_tableWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.aUser_tableWidget.setStyleSheet("QTableWidget{ \n"
                                             "  width: 100%;\n"
                                             "   padding: 15px;\n"
                                             "  text-align: left;\n"
                                             "color: white;\n"
                                             "}\n"
                                             "\n"
                                             "\n"
                                             "QHeaderView::section {\n"
                                             "color:white;\n"
                                             "    background-color: #646464;\n"
                                             "    padding: 4px;\n"
                                             "    border: 1px solid black;\n"
                                             "    font-size: 16px;\n"
                                             "font-weight:bold;\n"
                                             "\n"
                                             "}\n"
                                             "\n"
                                             "QTableWidget {\n"
                                             "    gridline-color: black;\n"
                                             "    font-size: 14px;\n"
                                             "}\n"
                                             "\n"
                                             "QTableWidget QTableCornerButton::section {\n"
                                             "    background-color: #646464;\n"
                                             "    border: 1px solid black;\n"
                                             "}")
        self.aUser_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aUser_tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.aUser_tableWidget.setObjectName("aUser_tableWidget")
        self.aUser_tableWidget.setColumnCount(5)
        self.aUser_tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.aUser_tableWidget.setHorizontalHeaderItem(4, item)
        self.aUser_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.aUser_tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.aUser_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.aUser_tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_10.addWidget(self.aUser_tableWidget)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem19)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.aStackedWidget.addWidget(self.aUsers_page)
        self.aHelp_page = QtWidgets.QWidget()
        self.aHelp_page.setObjectName("aHelp_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.aHelp_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.aHelp_label = QtWidgets.QLabel(self.aHelp_page)
        self.aHelp_label.setObjectName("aHelp_label")
        self.verticalLayout_6.addWidget(self.aHelp_label)
        self.aStackedWidget.addWidget(self.aHelp_page)
        self.verticalLayout_2.addWidget(self.aStackedWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        adminMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(adminMain)
        self.aStackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(adminMain)

        self.aCamera_pushButton.clicked.connect(self.openVideo)

    def openVideo(self):
        filename, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Open Video")
        if filename != '':
            #pixmap = QtGui.QPixmap(filename)
            #pixmap = pixmap.scaled(self.aVideo_label.width(), self.aVideo_label.height(), QtCore.Qt.KeepAspectRatio)
            self.aVideo_label.setMedia(QMediaContent(QUrl.fromLocalFile(filename)))
            self.aVideo_label.setAlignment(QtCore.Qt.AlignCenter)



    def retranslateUi(self, adminMain):
        _translate = QtCore.QCoreApplication.translate
        adminMain.setWindowTitle(_translate("adminMain", "MainWindow"))
        self.aCamera_toolButton.setText(_translate("adminMain", "Camera"))
        self.aAlarm_toolButton.setText(_translate("adminMain", "Alarm"))
        self.aStorage_toolButton.setText(_translate("adminMain", "Storage"))
        self.aAccount_toolButton.setText(_translate("adminMain", "Account"))
        self.aHelp_toolButton.setText(_translate("adminMain", "Help"))
        self.aLogout_toolButton.setText(_translate("adminMain", "Logout"))
        self.aUsers_toolButton.setText(_translate("adminMain", "Users"))
        self.aTitle_label.setText(_translate("adminMain", "SURVEILIA"))
        self.aCamera_pushButton.setText(_translate("adminMain", "Video/Image"))
        self.aAlarmHistory_label.setText(_translate("adminMain", "ALARM HISTORY"))
        self.aAlarm_tableWidget.setSortingEnabled(True)
        item = self.aAlarm_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aAlarm_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aAlarm_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aAlarm_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aAlarm_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aAlarm_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("adminMain", "ID"))
        item = self.aAlarm_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("adminMain", "Camera ID"))
        item = self.aAlarm_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("adminMain", "Time"))
        item = self.aAlarm_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("adminMain", "Alarm Description"))
        item = self.aAlarm_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("adminMain", "Anomaly Clip"))
        self.aStorage_label.setText(_translate("adminMain", "STORAGE"))
        self.aShow_label.setText(_translate("adminMain", "        Show:"))
        self.aAnomalyClip_checkBox.setText(_translate("adminMain", "Anomaly Clip"))
        self.aCameraFeed_checkBox.setText(_translate("adminMain", "Camera Feed"))
        item = self.aStorage_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aStorage_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aStorage_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aStorage_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aStorage_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aStorage_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aStorage_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("adminMain", "ID"))
        item = self.aStorage_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("adminMain", "Filename"))
        item = self.aStorage_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("adminMain", "Date"))
        item = self.aStorage_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("adminMain", "Size"))
        self.aAccountInfo_label.setText(_translate("adminMain", "ACCOUNT INFORMATION"))
        self.aUsername_label.setText(_translate("adminMain", "Username:"))
        self.aUsername_lineEdit.setText(_translate("adminMain", "Ifrah Tehleel"))
        self.aPassword_label.setText(_translate("adminMain", "Password:"))
        self.aPassword_lineEdit.setText(_translate("adminMain", "Ifrah"))
        self.aContactInfo_label.setText(_translate("adminMain", "Contact Info:"))
        self.aContactInfo_lineEdit.setText(_translate("adminMain", "+923014474797"))
        self.aAddress_label.setText(_translate("adminMain", "Address:"))
        self.aAddress_lineEdit.setHtml(_translate("adminMain",
                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'century gothic\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
                                                  "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.21053pt;\">49-A , Wapda Town, Lahore</span></p>\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.21053pt;\"><br /></p></body></html>"))
        self.aEdit_pushButton.setText(_translate("adminMain", "EDIT"))
        self.aUserInfo_label.setText(_translate("adminMain", "  USERS INFORMATION"))
        self.aUserAdd_pushButton.setText(_translate("adminMain", "ADD"))
        self.aUserDelete_pushButton.setText(_translate("adminMain", "DELETE"))
        item = self.aUser_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aUser_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aUser_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aUser_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aUser_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("adminMain", "New Row"))
        item = self.aUser_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("adminMain", "ID"))
        item = self.aUser_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("adminMain", "Name"))
        item = self.aUser_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("adminMain", "Password"))
        item = self.aUser_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("adminMain", "Contact Info"))
        item = self.aUser_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("adminMain", "Address"))
        self.aHelp_label.setText(_translate("adminMain",
                                            "                                                                               HELP SECTION"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    adminMain = QtWidgets.QMainWindow()
    ui = Ui_adminMain()
    ui.setupUi(adminMain)
    adminMain.show()
    sys.exit(app.exec_())
