# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loggedoutscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loggedoutscreen(object):
    def setupUi(self, loggedoutscreen):
        loggedoutscreen.setObjectName("loggedoutscreen")
        loggedoutscreen.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loggedoutscreen.sizePolicy().hasHeightForWidth())
        loggedoutscreen.setSizePolicy(sizePolicy)
        loggedoutscreen.setMinimumSize(QtCore.QSize(1000, 800))
        loggedoutscreen.setMaximumSize(QtCore.QSize(1000, 800))
        loggedoutscreen.setSizeIncrement(QtCore.QSize(0, 0))
        loggedoutscreen.setStyleSheet("*{\n"
                                      "font-family: century gothic;\n"
                                      "font-size: 30px;\n"
                                      "background-color:#201f1f;\n"
                                      "}\n"
                                      "QFrame{\n"
                                      "background: #605E5C ;\n"
                                      "border-radius:10px;\n"
                                      "\n"
                                      "}\n"
                                      "QLabel{\n"
                                      "color:white;\n"
                                      "font-weight: bold;\n"
                                      "}\n"
                                      "QToolButton{\n"
                                      "background:white;\n"
                                      "border-radius:60px;\n"
                                      "}\n"
                                      "QLineEdit{\n"
                                      "background: transparent;\n"
                                      "border:none;\n"
                                      "color:BLACK;\n"
                                      "border-bottom:1px solid black;\n"
                                      "font-size:20px;\n"
                                      "}\n"
                                      "QPushButton{\n"
                                      "font-size:18px;\n"
                                      "font-weight:bold;\n"
                                      "color:white ;\n"
                                      "background:#201f1f;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "color:white;\n"
                                      "background-color:black;\n"
                                      "}\n"
                                      "#logoLabel{\n"
                                      "background:transparent;\n"
                                      "}")
        self.centralwidget = QtWidgets.QWidget(loggedoutscreen)
        self.centralwidget.setObjectName("centralwidget")
        self.loginForm_frame = QtWidgets.QFrame(self.centralwidget)
        self.loginForm_frame.setGeometry(QtCore.QRect(330, 190, 350, 450))
        self.loginForm_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginForm_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginForm_frame.setObjectName("loginForm_frame")
        self.title_label = QtWidgets.QLabel(self.loginForm_frame)
        self.title_label.setGeometry(QtCore.QRect(100, 70, 140, 40))
        self.title_label.setObjectName("title_label")
        self.loginAgain_pushButton = QtWidgets.QPushButton(self.loginForm_frame)
        self.loginAgain_pushButton.setGeometry(QtCore.QRect(90, 290, 160, 40))
        self.loginAgain_pushButton.setObjectName("loginAgain_pushButton")
        self.loggedOut_label = QtWidgets.QLabel(self.loginForm_frame)
        self.loggedOut_label.setGeometry(QtCore.QRect(50, 180, 251, 31))
        self.loggedOut_label.setStyleSheet("font-size: 18px;")
        self.loggedOut_label.setObjectName("loggedOut_label")
        self.cancel_pushButton = QtWidgets.QPushButton(self.loginForm_frame)
        self.cancel_pushButton.setGeometry(QtCore.QRect(90, 350, 160, 40))
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(430, 120, 150, 100))
        self.logo_label.setStyleSheet("background: transparent;")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/logo/surveilialogo.PNG"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.logo_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.logo_toolButton.setGeometry(QtCore.QRect(440, 110, 120, 120))
        self.logo_toolButton.setText("")
        self.logo_toolButton.setObjectName("logo_toolButton")
        self.loginForm_frame.raise_()
        self.logo_toolButton.raise_()
        self.logo_label.raise_()
        loggedoutscreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(loggedoutscreen)
        QtCore.QMetaObject.connectSlotsByName(loggedoutscreen)

    def retranslateUi(self, loggedoutscreen):
        _translate = QtCore.QCoreApplication.translate
        loggedoutscreen.setWindowTitle(_translate("loggedoutscreen", "MainWindow"))
        self.title_label.setText(_translate("loggedoutscreen", "SURVEILIA"))
        self.loginAgain_pushButton.setText(_translate("loggedoutscreen", "LOGIN AGAIN"))
        self.loggedOut_label.setText(_translate("loggedoutscreen", "You have been logged out!"))
        self.cancel_pushButton.setText(_translate("loggedoutscreen", "CANCEL"))


import resource01

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loggedoutscreen = QtWidgets.QMainWindow()
    ui = Ui_loggedoutscreen()
    ui.setupUi(loggedoutscreen)
    loggedoutscreen.show()
    sys.exit(app.exec_())
