# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from adminMain import Ui_adminMain

class Ui_loginscreen(object):
    def setupUi(self, loginscreen):
        loginscreen.setObjectName("loginscreen")
        loginscreen.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(loginscreen.sizePolicy().hasHeightForWidth())
        loginscreen.setSizePolicy(sizePolicy)
        loginscreen.setMinimumSize(QtCore.QSize(1000, 800))
        loginscreen.setMaximumSize(QtCore.QSize(1000, 800))
        loginscreen.setSizeIncrement(QtCore.QSize(0, 0))
        loginscreen.setStyleSheet("*{\n"
                                  "font-family: century gothic;\n"
                                  "font-size: 30px;\n"
                                  "background-color:#201f1f;\n"
                                  "}\n"
                                  "QFrame{\n"
                                  "background: #605E5C ;\n"
                                  "border-radius:10px;\n"
                                  "\n"
                                  "}\n"
                                  "QLabel{\n"
                                  "color:white;\n"
                                  "font-weight: bold;\n"
                                  "}\n"
                                  "QToolButton{\n"
                                  "background:white;\n"
                                  "border-radius:60px;\n"
                                  "}\n"
                                  "QLineEdit{\n"
                                  "background: transparent;\n"
                                  "border:none;\n"
                                  "color:BLACK;\n"
                                  "border-bottom:1px solid black;\n"
                                  "font-size:20px;\n"
                                  "}\n"
                                  "QPushButton{\n"
                                  "font-size:18px;\n"
                                  "font-weight:bold;\n"
                                  "color:white ;\n"
                                  "background:#201f1f;\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "color:white;\n"
                                  "background-color:black;\n"
                                  "}\n"
                                  "#logoLabel{\n"
                                  "background:transparent;\n"
                                  "}")
        self.centralwidget = QtWidgets.QWidget(loginscreen)
        self.centralwidget.setObjectName("centralwidget")
        self.loginForm_frame = QtWidgets.QFrame(self.centralwidget)
        self.loginForm_frame.setGeometry(QtCore.QRect(330, 190, 350, 481))
        self.loginForm_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.loginForm_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginForm_frame.setObjectName("loginForm_frame")
        self.title_label = QtWidgets.QLabel(self.loginForm_frame)
        self.title_label.setGeometry(QtCore.QRect(100, 70, 140, 40))
        self.title_label.setObjectName("title_label")
        self.username_field = QtWidgets.QLineEdit(self.loginForm_frame)
        self.username_field.setGeometry(QtCore.QRect(50, 180, 240, 30))
        self.username_field.setObjectName("username_field")
        self.password_field = QtWidgets.QLineEdit(self.loginForm_frame)
        self.password_field.setGeometry(QtCore.QRect(50, 240, 240, 30))
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.login_pushButton = QtWidgets.QPushButton(self.loginForm_frame)
        self.login_pushButton.setGeometry(QtCore.QRect(90, 390, 160, 40))
        self.login_pushButton.setObjectName("login_pushButton")
        self.admin_radioButton = QtWidgets.QRadioButton(self.loginForm_frame)
        self.admin_radioButton.setGeometry(QtCore.QRect(170, 330, 92, 16))
        self.admin_radioButton.setStyleSheet("QRadioButton{\n"
                                             "color:#302F2E;\n"
                                             "font-size:16px;\n"
                                             "background:transparent;\n"
                                             "\n"
                                             "\n"
                                             "}")
        self.admin_radioButton.setObjectName("admin_radioButton")
        self.user_radioButton = QtWidgets.QRadioButton(self.loginForm_frame)
        self.user_radioButton.setGeometry(QtCore.QRect(170, 305, 61, 20))
        self.user_radioButton.setStyleSheet("QRadioButton{\n"
                                            "color:#302F2E;\n"
                                            "font-size:16px;\n"
                                            "background:transparent;\n"
                                            "\n"
                                            "}")
        self.user_radioButton.setObjectName("user_radioButton")
        self.loginas_label = QtWidgets.QLabel(self.loginForm_frame)
        self.loginas_label.setGeometry(QtCore.QRect(60, 300, 81, 31))
        self.loginas_label.setStyleSheet("*{\n"
                                         "background: transparent;\n"
                                         "border:none;\n"
                                         "color:#302F2E;\n"
                                         "font-size:18px;\n"
                                         "font-weight:500;\n"
                                         "\n"
                                         "}")
        self.loginas_label.setObjectName("loginas_label")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(430, 120, 150, 100))
        self.logo_label.setStyleSheet("background: transparent;")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(":/logo/surveilialogo.PNG"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.logo_toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.logo_toolButton.setGeometry(QtCore.QRect(440, 110, 120, 120))
        self.logo_toolButton.setText("")
        self.logo_toolButton.setObjectName("logo_toolButton")
        self.loginForm_frame.raise_()
        self.logo_toolButton.raise_()
        self.logo_label.raise_()
        loginscreen.setCentralWidget(self.centralwidget)

        self.login_pushButton.clicked.connect(lambda: self.authenticate())

        self.retranslateUi(loginscreen)
        QtCore.QMetaObject.connectSlotsByName(loginscreen)

    def retranslateUi(self, loginscreen):
        _translate = QtCore.QCoreApplication.translate
        loginscreen.setWindowTitle(_translate("loginscreen", "MainWindow"))
        self.title_label.setText(_translate("loginscreen", "SURVEILIA"))
        self.username_field.setPlaceholderText(_translate("loginscreen", "Username"))
        self.password_field.setPlaceholderText(_translate("loginscreen", "Password"))
        self.login_pushButton.setText(_translate("loginscreen", "LOGIN"))
        self.admin_radioButton.setText(_translate("loginscreen", "Admin"))
        self.user_radioButton.setText(_translate("loginscreen", "User"))
        self.loginas_label.setText(_translate("loginscreen", "Login as:"))


    def authenticate(self):
        # username = self.username_field.text()
        # password = self.password_field.text()
        #
        # if username == 'ifrah' and password == 'password':
        #     print("LOGIN")
            self.app = QtWidgets.QApplication(sys.argv)
            self.adminMain = QtWidgets.QMainWindow()
            self.ui = Ui_adminMain()
            self.ui.setupUi(self.adminMain)
            self.adminMain.show()

import resource01

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    loginscreen = QtWidgets.QMainWindow()
    ui = Ui_loginscreen()
    ui.setupUi(loginscreen)
    loginscreen.show()
    sys.exit(app.exec_())
