# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userMain(object):
    def setupUi(self, userMain):
        userMain.setObjectName("userMain")
        userMain.resize(1048, 813)
        userMain.setMinimumSize(QtCore.QSize(1000, 800))
        userMain.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"background-color:#484644;\n"
"}\n"
"QLineEdit, QTextEdit{\n"
"background: #201f1f;\n"
"border:#201f1f;\n"
"color:white;\n"
"font-size:18px;\n"
"}\n"
"QLabel{\n"
"color: white;\n"
"font-size: 18px;\n"
"\n"
"}\n"
"QPushButton, QToolButton{\n"
"font-weight:bold;\n"
"color:white ;\n"
"background:#201f1f;\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:black;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(userMain)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uMenuBar = QtWidgets.QWidget(self.centralwidget)
        self.uMenuBar.setMinimumSize(QtCore.QSize(80, 0))
        self.uMenuBar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.uMenuBar.setStyleSheet("*{background: #201f1f;}\n"
"QToolButton:hover{\n"
"     background-color:#3b3a3a;\n"
"}\n"
"QToolButton:pressed{\n"
"     background-color: #605E5C ;     \n"
"}")
        self.uMenuBar.setObjectName("uMenuBar")
        self.ucamera_toolButton = QtWidgets.QToolButton(self.uMenuBar)
        self.ucamera_toolButton.setGeometry(QtCore.QRect(0, 10, 80, 71))
        self.ucamera_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.ucamera_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.ucamera_toolButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("camera-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ucamera_toolButton.setIcon(icon)
        self.ucamera_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.ucamera_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ucamera_toolButton.setObjectName("ucamera_toolButton")
        self.ualarm_toolButton = QtWidgets.QToolButton(self.uMenuBar)
        self.ualarm_toolButton.setGeometry(QtCore.QRect(0, 80, 80, 71))
        self.ualarm_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.ualarm_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.ualarm_toolButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("alarm-clock-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ualarm_toolButton.setIcon(icon1)
        self.ualarm_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.ualarm_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ualarm_toolButton.setObjectName("ualarm_toolButton")
        self.ustorage_toolButton = QtWidgets.QToolButton(self.uMenuBar)
        self.ustorage_toolButton.setGeometry(QtCore.QRect(0, 150, 80, 71))
        self.ustorage_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.ustorage_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.ustorage_toolButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("database-5-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ustorage_toolButton.setIcon(icon2)
        self.ustorage_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.ustorage_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ustorage_toolButton.setObjectName("ustorage_toolButton")
        self.uaccount_toolButton = QtWidgets.QToolButton(self.uMenuBar)
        self.uaccount_toolButton.setGeometry(QtCore.QRect(0, 220, 80, 71))
        self.uaccount_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.uaccount_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.uaccount_toolButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("contacts-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uaccount_toolButton.setIcon(icon3)
        self.uaccount_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.uaccount_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.uaccount_toolButton.setObjectName("uaccount_toolButton")
        self.uhelp_toolButton = QtWidgets.QToolButton(self.uMenuBar)
        self.uhelp_toolButton.setGeometry(QtCore.QRect(0, 290, 80, 71))
        self.uhelp_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.uhelp_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.uhelp_toolButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("question-mark-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uhelp_toolButton.setIcon(icon4)
        self.uhelp_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.uhelp_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.uhelp_toolButton.setObjectName("uhelp_toolButton")
        self.ulogout_toolButton = QtWidgets.QToolButton(self.uMenuBar)
        self.ulogout_toolButton.setGeometry(QtCore.QRect(0, 360, 80, 71))
        self.ulogout_toolButton.setMinimumSize(QtCore.QSize(80, 0))
        self.ulogout_toolButton.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("century gothic")
        font.setBold(True)
        font.setWeight(75)
        self.ulogout_toolButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("logout-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ulogout_toolButton.setIcon(icon5)
        self.ulogout_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.ulogout_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ulogout_toolButton.setObjectName("ulogout_toolButton")
        self.horizontalLayout_2.addWidget(self.uMenuBar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uTitleBar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uTitleBar.sizePolicy().hasHeightForWidth())
        self.uTitleBar.setSizePolicy(sizePolicy)
        self.uTitleBar.setMinimumSize(QtCore.QSize(0, 80))
        self.uTitleBar.setMaximumSize(QtCore.QSize(16777215, 80))
        self.uTitleBar.setStyleSheet("background: #201f1f;\n"
"font-size: 24px;")
        self.uTitleBar.setObjectName("uTitleBar")
        self.uTitle_label = QtWidgets.QLabel(self.uTitleBar)
        self.uTitle_label.setGeometry(QtCore.QRect(60, 30, 121, 21))
        self.uTitle_label.setObjectName("uTitle_label")
        self.verticalLayout_2.addWidget(self.uTitleBar)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.uStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.uStackedWidget.setStyleSheet("QTableWidget{ \n"
"  width: 100%;\n"
"   padding: 15px;\n"
"  text-align: left;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"color:white;\n"
"    background-color: #646464;\n"
"    padding: 4px;\n"
"    border: 1px solid black;\n"
"    font-size: 16px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: black;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid black;\n"
"}")
        self.uStackedWidget.setObjectName("uStackedWidget")
        self.uCamera_page = QtWidgets.QWidget()
        self.uCamera_page.setObjectName("uCamera_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.uCamera_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.uCamera_label = QtWidgets.QLabel(self.uCamera_page)
        self.uCamera_label.setObjectName("uCamera_label")
        self.verticalLayout_7.addWidget(self.uCamera_label)
        self.uStackedWidget.addWidget(self.uCamera_page)
        self.uAlarm_page = QtWidgets.QWidget()
        self.uAlarm_page.setObjectName("uAlarm_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.uAlarm_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.uAlarmHistory_label = QtWidgets.QLabel(self.uAlarm_page)
        self.uAlarmHistory_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
"font-size:24px")
        self.uAlarmHistory_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uAlarmHistory_label.setObjectName("uAlarmHistory_label")
        self.horizontalLayout_3.addWidget(self.uAlarmHistory_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.uAlarm_tableWidget = QtWidgets.QTableWidget(self.uAlarm_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uAlarm_tableWidget.sizePolicy().hasHeightForWidth())
        self.uAlarm_tableWidget.setSizePolicy(sizePolicy)
        self.uAlarm_tableWidget.setMinimumSize(QtCore.QSize(800, 0))
        self.uAlarm_tableWidget.setStyleSheet("QTableWidget{ \n"
"  width: 100%;\n"
"   padding: 15px;\n"
"  text-align: left;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"color:white;\n"
"    background-color: #646464;\n"
"    padding: 4px;\n"
"    border: 1px solid black;\n"
"    font-size: 16px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: black;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid black;\n"
"}")
        self.uAlarm_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.uAlarm_tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.uAlarm_tableWidget.setObjectName("uAlarm_tableWidget")
        self.uAlarm_tableWidget.setColumnCount(5)
        self.uAlarm_tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.uAlarm_tableWidget.setHorizontalHeaderItem(4, item)
        self.uAlarm_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.uAlarm_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.uAlarm_tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.uAlarm_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.uAlarm_tableWidget.verticalHeader().setVisible(False)
        self.uAlarm_tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.horizontalLayout.addWidget(self.uAlarm_tableWidget)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.uStackedWidget.addWidget(self.uAlarm_page)
        self.uStorage_page = QtWidgets.QWidget()
        self.uStorage_page.setObjectName("uStorage_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.uStorage_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.uStorage_label = QtWidgets.QLabel(self.uStorage_page)
        self.uStorage_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
"font-size:24px")
        self.uStorage_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uStorage_label.setObjectName("uStorage_label")
        self.horizontalLayout_4.addWidget(self.uStorage_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uShow_label = QtWidgets.QLabel(self.uStorage_page)
        self.uShow_label.setObjectName("uShow_label")
        self.horizontalLayout_5.addWidget(self.uShow_label)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.uAnomalyClip_checkBox = QtWidgets.QCheckBox(self.uStorage_page)
        self.uAnomalyClip_checkBox.setStyleSheet("\n"
"font-size:16px;\n"
"color:white;")
        self.uAnomalyClip_checkBox.setObjectName("uAnomalyClip_checkBox")
        self.horizontalLayout_5.addWidget(self.uAnomalyClip_checkBox)
        self.uCameraFeed_checkBox = QtWidgets.QCheckBox(self.uStorage_page)
        self.uCameraFeed_checkBox.setStyleSheet("\n"
"font-size:16px;\n"
"color:white;")
        self.uCameraFeed_checkBox.setIconSize(QtCore.QSize(30, 30))
        self.uCameraFeed_checkBox.setChecked(False)
        self.uCameraFeed_checkBox.setAutoRepeat(False)
        self.uCameraFeed_checkBox.setAutoExclusive(False)
        self.uCameraFeed_checkBox.setTristate(False)
        self.uCameraFeed_checkBox.setObjectName("uCameraFeed_checkBox")
        self.horizontalLayout_5.addWidget(self.uCameraFeed_checkBox)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.uStorage_tableWidget = QtWidgets.QTableWidget(self.uStorage_page)
        self.uStorage_tableWidget.setMinimumSize(QtCore.QSize(700, 0))
        self.uStorage_tableWidget.setStyleSheet("QTableWidget{ \n"
"  width: 100%;\n"
"   padding: 15px;\n"
"  text-align: left;\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section {\n"
"color:white;\n"
"    background-color: #646464;\n"
"    padding: 4px;\n"
"    border: 1px solid black;\n"
"    font-size: 16px;\n"
"font-weight:bold;\n"
"\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: black;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: #646464;\n"
"    border: 1px solid black;\n"
"}")
        self.uStorage_tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.uStorage_tableWidget.setObjectName("uStorage_tableWidget")
        self.uStorage_tableWidget.setColumnCount(4)
        self.uStorage_tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.uStorage_tableWidget.setHorizontalHeaderItem(3, item)
        self.uStorage_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.uStorage_tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.uStorage_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.uStorage_tableWidget.verticalHeader().setVisible(False)
        self.uStorage_tableWidget.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_6.addWidget(self.uStorage_tableWidget)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.uStackedWidget.addWidget(self.uStorage_page)
        self.uAccount_page = QtWidgets.QWidget()
        self.uAccount_page.setObjectName("uAccount_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.uAccount_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.uAccount_form = QtWidgets.QFormLayout()
        self.uAccount_form.setObjectName("uAccount_form")
        self.uAccountInfo_label = QtWidgets.QLabel(self.uAccount_page)
        self.uAccountInfo_label.setStyleSheet("FONT-WEIGHT:BOLD;\n"
"font-size:24px;")
        self.uAccountInfo_label.setObjectName("uAccountInfo_label")
        self.uAccount_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.uAccountInfo_label)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.uAccount_form.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem12)
        self.uUsername_label = QtWidgets.QLabel(self.uAccount_page)
        self.uUsername_label.setObjectName("uUsername_label")
        self.uAccount_form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.uUsername_label)
        self.uUsername_lineEdit = QtWidgets.QLineEdit(self.uAccount_page)
        self.uUsername_lineEdit.setObjectName("uUsername_lineEdit")
        self.uAccount_form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.uUsername_lineEdit)
        self.uPassword_label = QtWidgets.QLabel(self.uAccount_page)
        self.uPassword_label.setObjectName("uPassword_label")
        self.uAccount_form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.uPassword_label)
        self.uPassword_lineEdit = QtWidgets.QLineEdit(self.uAccount_page)
        self.uPassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.uPassword_lineEdit.setObjectName("uPassword_lineEdit")
        self.uAccount_form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.uPassword_lineEdit)
        self.uContactInfo_label = QtWidgets.QLabel(self.uAccount_page)
        self.uContactInfo_label.setObjectName("uContactInfo_label")
        self.uAccount_form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.uContactInfo_label)
        self.uContactInfo_lineEdit = QtWidgets.QLineEdit(self.uAccount_page)
        self.uContactInfo_lineEdit.setObjectName("uContactInfo_lineEdit")
        self.uAccount_form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.uContactInfo_lineEdit)
        self.uAddress_label = QtWidgets.QLabel(self.uAccount_page)
        self.uAddress_label.setObjectName("uAddress_label")
        self.uAccount_form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.uAddress_label)
        self.uAddress_lineEdit = QtWidgets.QTextEdit(self.uAccount_page)
        self.uAddress_lineEdit.setObjectName("uAddress_lineEdit")
        self.uAccount_form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.uAddress_lineEdit)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.uAccount_form.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem13)
        self.horizontalLayout_7.addLayout(self.uAccount_form)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.uStackedWidget.addWidget(self.uAccount_page)
        self.uHelp_page = QtWidgets.QWidget()
        self.uHelp_page.setObjectName("uHelp_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.uHelp_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.uHelp_label = QtWidgets.QLabel(self.uHelp_page)
        self.uHelp_label.setObjectName("uHelp_label")
        self.verticalLayout_6.addWidget(self.uHelp_label)
        self.uStackedWidget.addWidget(self.uHelp_page)
        self.verticalLayout_2.addWidget(self.uStackedWidget)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        userMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(userMain)
        self.uStackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(userMain)

    def retranslateUi(self, userMain):
        _translate = QtCore.QCoreApplication.translate
        userMain.setWindowTitle(_translate("userMain", "MainWindow"))
        self.ucamera_toolButton.setText(_translate("userMain", "Camera"))
        self.ualarm_toolButton.setText(_translate("userMain", "Alarm"))
        self.ustorage_toolButton.setText(_translate("userMain", "Storage"))
        self.uaccount_toolButton.setText(_translate("userMain", "Account"))
        self.uhelp_toolButton.setText(_translate("userMain", "Help"))
        self.ulogout_toolButton.setText(_translate("userMain", "Logout"))
        self.uTitle_label.setText(_translate("userMain", "SURVEILIA"))
        self.uCamera_label.setText(_translate("userMain", "                                   CAMERA SECTION"))
        self.uAlarmHistory_label.setText(_translate("userMain", "ALARM HISTORY"))
        self.uAlarm_tableWidget.setSortingEnabled(True)
        item = self.uAlarm_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("userMain", "New Row"))
        item = self.uAlarm_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("userMain", "New Row"))
        item = self.uAlarm_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("userMain", "New Row"))
        item = self.uAlarm_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("userMain", "New Row"))
        item = self.uAlarm_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("userMain", "New Row"))
        item = self.uAlarm_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("userMain", "ID"))
        item = self.uAlarm_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("userMain", "Camera ID"))
        item = self.uAlarm_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("userMain", "Time"))
        item = self.uAlarm_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("userMain", "Alarm Description"))
        item = self.uAlarm_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("userMain", "Anomaly Clip"))
        self.uStorage_label.setText(_translate("userMain", "STORAGE"))
        self.uShow_label.setText(_translate("userMain", "        Show:"))
        self.uAnomalyClip_checkBox.setText(_translate("userMain", "Anomaly Clip"))
        self.uCameraFeed_checkBox.setText(_translate("userMain", "Camera Feed"))
        item = self.uStorage_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("userMain", "New Row"))
        item = self.uStorage_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("userMain", "New Row"))
        item = self.uStorage_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("userMain", "New Row"))
        item = self.uStorage_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("userMain", "New Row"))
        item = self.uStorage_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("userMain", "New Row"))
        item = self.uStorage_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("userMain", "New Row"))
        item = self.uStorage_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("userMain", "ID"))
        item = self.uStorage_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("userMain", "Filename"))
        item = self.uStorage_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("userMain", "Date"))
        item = self.uStorage_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("userMain", "Size"))
        self.uAccountInfo_label.setText(_translate("userMain", "ACCOUNT INFORMATION"))
        self.uUsername_label.setText(_translate("userMain", "Username:"))
        self.uUsername_lineEdit.setText(_translate("userMain", "Ifrah Tehleel"))
        self.uPassword_label.setText(_translate("userMain", "Password:"))
        self.uPassword_lineEdit.setText(_translate("userMain", "Ifrah"))
        self.uContactInfo_label.setText(_translate("userMain", "Contact Info:"))
        self.uContactInfo_lineEdit.setText(_translate("userMain", "+923014474797"))
        self.uAddress_label.setText(_translate("userMain", "Address:"))
        self.uAddress_lineEdit.setHtml(_translate("userMain", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'century gothic\'; font-size:18px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.21053pt;\">49-A , Wapda Town, Lahore</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.21053pt;\"><br /></p></body></html>"))
        self.uHelp_label.setText(_translate("userMain", "                                                                               HELP SECTION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    userMain = QtWidgets.QMainWindow()
    ui = Ui_userMain()
    ui.setupUi(userMain)
    userMain.show()
    sys.exit(app.exec_())
